### ISSUE TITLE
Grant write access for this repository to me

### ISSUE THREAD

**Issue by zgoethel12** [team-jgloom/jgloom-io#1]
#### Option A:
Grant write access to me for every repo individually

#### Option B:
Make me a team owner so I get full access

I want to start working on some image loading systems

**Comment by zgoethel12** [comment]
I've cloned the repository and am working on it locally.  I'll create the `dev` and `feat` branches.

**Comment by zgoethel12** [comment]
I have now created a system capable of loading all of the planned image formats.  In order to load TIFF images, I needed to add an additional plugin to the `gradle.build` file.

**Comment by zgoethel12** [comment]
I have forked the repository to [zgoethel12/jgloom-io](https://github.com/zgoethel12/jgloom-io/tree/feat/images) and pushed my changes to branch `feat/images`.  I will create a pull request once write permissions are granted.

**Comment by ecumene-software** [comment]
Done!
